version: "3"
services:
  next-js-app:
    image: docker-nextjs-dev:development
    build: .
    container_name: frontend-app
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./components:/app/components
      - ./data:/app/data
      - ./public:/app/public
      - ./styles:/app/styles
