version: "3"
services:
  next-js-app:
    build: .
    command: "npm run dev"
    container_name: development
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./components:/app/components
      - ./data:/app/data
      - ./public:/app/public
      - ./styles:/app/styles
      - ./node_modules:/app/node_modules
